name: Feature Request
description: Verbesserung vorschlagen
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Welches Problem soll gelöst werden?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Lösungsvorschlag
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativen
